2021/05/24 08:30:21 [error] 23#23: *1 open() "/usr/share/nginx/html/v1/stats/8hours/yesterday" failed (2: No such file or directory), client: 172.23.0.1, server: localhost, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", host: "localhost:8092"
2021/05/24 08:31:31 [error] 23#23: *2 open() "/usr/share/nginx/html/v1/stats/8hours/yesterday" failed (2: No such file or directory), client: 172.23.0.1, server: localhost, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", host: "localhost:8092"
2021/05/24 08:38:31 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", upstream: "fastcgi://172.23.0.6:9000", host: "localhost:8092"
2021/05/24 08:39:04 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", upstream: "fastcgi://172.23.0.6:9000", host: "localhost:8092"
2021/05/24 08:39:05 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", upstream: "fastcgi://172.23.0.6:9000", host: "localhost:8092"
2021/05/24 08:40:45 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", upstream: "fastcgi://172.23.0.6:9000", host: "localhost:8092"
2021/05/24 08:40:54 [error] 28#28: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", upstream: "fastcgi://172.23.0.6:9000", host: "localhost:8092"
2021/05/24 08:40:57 [error] 28#28: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", upstream: "fastcgi://172.23.0.6:9000", host: "localhost:8092"
2021/05/24 08:45:38 [error] 28#28: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", upstream: "fastcgi://172.23.0.6:9000", host: "localhost:8092"
2021/05/24 08:46:13 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", upstream: "fastcgi://172.23.0.6:9000", host: "localhost:8092"
2021/05/24 08:46:14 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", upstream: "fastcgi://172.23.0.6:9000", host: "localhost:8092"
2021/05/24 08:46:23 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET /v1/stats/8hours/yesterday HTTP/1.1", upstream: "fastcgi://172.23.0.6:9000", host: "localhost:8092"
